server:
  port: 8080

spring:
  application:
    name: sss-sync-system

  jackson:
    time-zone: Asia/Shanghai

  mail:
    host: smtp.163.com
    port: 465
    username: mo1lly@163.com
    password: "TJcALtY5z39gyDax"
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true

sss:
  id:
    workerId: 1

  jwt:
    issuer: "sss-sync"
    secret: "sss-sync-secret-key-please-change-32bytes"
    accessTokenExpireMinutes: 240

  datasource:
    mysql:
      url: jdbc:mysql://127.0.0.1:3306/sss_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false
      username: root
      password: "myPassWord++"
      driver-class-name: com.mysql.cj.jdbc.Driver
    postgres:
      url: jdbc:postgresql://127.0.0.1:5432/sss_db
      username: postgres
      password: "myPassWord++"
      driver-class-name: org.postgresql.Driver
    sqlserver:
      url: jdbc:sqlserver://127.0.0.1:1433;databaseName=sss_db;encrypt=false;trustServerCertificate=true
      username: sa
      password: "myPassWord++"
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  sync:
    enabled: true
    pollIntervalMillis: 10000
    batchSize: 200
    scheduled:
      enabled: false
      fixedDelayMillis: 10000

  mail:
    enabled: true
    from: "mo1lly@163.com"
    adminTo: "2107480012@qq.com"
    conflictViewBaseUrl: "http://localhost:8080"

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl