server:
  port: 8080

spring:
  application:
    name: sss-sync-system

  jackson:
    time-zone: Asia/Shanghai

  mail:
    host: smtp.163.com
    port: 465
    username: mo1lly@163.com
    password: "TJcALtY5z39gyDax"
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
sss:
  jwt:
    issuer: "sss-sync"
    secret: "sss-sync-secret-key-please-change-32bytes"
    accessTokenExpireMinutes: 240

  datasource:
    mysql:
      url: jdbc:mysql://127.0.0.1:3306/sss_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false
      username: root
      password: "myPassWord++"
      driver-class-name: com.mysql.cj.jdbc.Driver
    postgres:
      url: jdbc:postgresql://127.0.0.1:5432/sss_db
      username: postgres
      password: "myPassWord++"
      driver-class-name: org.postgresql.Driver
    sqlserver:
      url: jdbc:sqlserver://127.0.0.1:1433;databaseName=sss_db;encrypt=false;trustServerCertificate=true
      username: sa
      password: "myPassWord++"
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    sync:
      enabled: false
      pollIntervalMillis: 1000        # 实时轮询间隔（1秒）
      batchSize: 200                  # 每次最多同步多少条 change_log
      scheduled:
        enabled: false
        fixedDelayMillis: 10000

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  mail:
    enabled: true
    from: "mo1lly@163.com"
    adminTo: "mo1lly@163.com"
    conflictViewBaseUrl: "http://localhost:8080"  # 邮件链接 base